version: '3.6'
services:
  # Postgres Database
  postgres-database:
    build:
      context: ./dockerfiles/database
      dockerfile: ./Dockerfile
    image: go_url_shortner_postgres:latest
    container_name: service-db-psql
    volumes:
      - /Users/abhishekp/workspace/docker_volume/database/postgres/data/:/var/lib/postgresql/data/
      - /Users/abhishekp/workspace/docker_volume/database/postgres/custom_files/:/root/custom_files/
    environment:
      - PGPASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "6000:5432"
    stdin_open: true #  docker attach container_id
    tty: true #  docker attach container_id
    networks:
      - default

    # Golang Application
  go-url-shortner-application:
      build:
        context: ./
        dockerfile: ./dockerfiles/app/Dockerfile
      image: go-url-shortner-application:latest
      container_name: go-url-shortner-application
      entrypoint: /bin/sh
      environment:
        # Stage Dependent values (Prod/Staging/Local)
        - HOSTNAME=localhost
        - ENVIRONMENT=test
        # Postgres Database Credentials
        - POSTGRES_DB_HOST=service-db-psql
        - POSTGRES_DB_NAME=go_url_shortner
        - POSTGRES_DB_PORT=5432
        - POSTGRES_DB_USERNAME=postgres
        - POSTGRES_DB_PASSWORD=123456
      ports:
        - "9000:8080"
      stdin_open: true #  docker attach container_id
      tty: true #  docker attach container_id
      networks:
        - default

networks:
  default:
    external:
      name: docker-internal-network