version: '3.7'
services:
  # Postgres Database
  postgres-database:
    image: postgres:13
    container_name: service-postgres-database
    volumes:
      - docker-postgres-database:/var/lib/postgresql/data/
    environment:
      - PGPASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "6000:5432"
    stdin_open: true #  docker attach container_id
    tty: true #  docker attach container_id
    networks:
      - default

    # Golang Application
  go-url-shortner-application:
      build:
        context: ./
        dockerfile: ./setup/dockerfiles/app/Dockerfile
      image: go-url-shortner-application:latest
      container_name: go-url-shortner-application
      entrypoint: /bin/sh
      depends_on:
        - postgres-database
      volumes:
        - ./setup/resource/:/root/workspace/GoUrlShortner/setup/resource/
      environment:
        # Stage Dependent values (Prod/Staging/Local)
        - HOSTNAME=localhost
        - ENVIRONMENT=local
        # Postgres Database Credentials
        - POSTGRES_DB_HOST=service-postgres-database
        - POSTGRES_DB_NAME=go_url_shortner
        - POSTGRES_DB_PORT=5432
        - POSTGRES_DB_USERNAME=gus_user
        - POSTGRES_DB_PASSWORD=gus_user@123
        # File conatining urls to mock valid urls being provided
        - MOCK_URL_FILE_PATH=/root/workspace/GoUrlShortner/setup/resource/URLS-200.txt
      ports:
        - "9000:8080"
      stdin_open: true #  docker attach container_id
      tty: true #  docker attach container_id
      networks:
        - default

networks:
  default:
    name: docker-internal-network

volumes:
  docker-postgres-database:
    name: docker-postgres-database
    external: true